/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package com.tyj.dao.demo.deviceGpsInfos.dao;

import cn.vansky.framework.core.dao.DaoMapper;
import cn.vansky.framework.core.orm.mybatis.annotation.SqlMapper;
import com.tyj.dao.demo.deviceGpsInfos.bo.DeviceGpsInfosCount;

import java.util.List;
import java.util.Map;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table `device_gps_infos_count`
 *
 * @mbggenerated 2015-12-30 16:45:19
 */
@SqlMapper
public interface DeviceGpsInfosCountMapper extends DaoMapper<DeviceGpsInfosCount, Integer> {

    void delByDeviceIdAndTime(Map<String, Object> params);

    List<DeviceGpsInfosCount> findParams(Map<String, Object> params);

    List<DeviceGpsInfosCount> findTotalAlarm(Map<String, Object> params);
}