/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package com.tyj.dao.demo.deviceGpsInfos.dao;

import cn.vansky.framework.core.dao.SqlMapDao;
import com.tyj.dao.demo.deviceGpsInfos.bo.DeviceGpsInfos;

import java.util.List;
import java.util.Map;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table `device_gps_infos`
 *
 * @mbggenerated 2015-12-09 08:31:58
 */
public interface DeviceGpsInfosDao extends SqlMapDao<DeviceGpsInfos, Integer> {

    List<DeviceGpsInfos> findDaySpeed(Map<String, Object> params);

    List<Map<String, Object>> findByDeviceIds(List<Integer> list);

    void delByDeviceIdAndTime(Map<String, Object> params);

    List<Map<String, Object>> findAlarmMessage(Map<String, Object> params);

    List<DeviceGpsInfos> findByDeviceIdAndTime(Map<String, Object> params);

    List<DeviceGpsInfos> findByDeviceIdAndTypes(Map<String, Object> params);

    void createPartition(Map<String, Object> params);

    List<DeviceGpsInfos> findLocation(Map<String, Object> params);
}