/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package com.tyj.dao.jhpt.deviceInfo.bo;

import org.springframework.beans.BeanUtils;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table `device_info`
 *
 * @mbggenerated 2015-12-10 09:17:05
 */
public class DeviceInfo extends DeviceInfoBase {

    public com.tyj.dao.demo.general.bo.DeviceInfo covert() {
        com.tyj.dao.demo.general.bo.DeviceInfo deviceInfo = new com.tyj.dao.demo.general.bo.DeviceInfo();
        BeanUtils.copyProperties(this, deviceInfo);
        return deviceInfo;
    }
}