/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package com.tyj.dao.jhpt.deviceInfo.bo;

import cn.vansky.framework.core.dao.FieldAccessVo;
import cn.vansky.framework.core.dao.TableDataConvertable;
import cn.vansky.framework.core.dao.annotation.ColumnDescription;
import cn.vansky.framework.core.dao.annotation.Id;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table `device_info`
 *
 * @mbggenerated 2015-12-10 09:17:05
 */
public abstract class DeviceInfoBase extends FieldAccessVo implements TableDataConvertable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.id
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_ID = "id";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.id
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_REMARK_ID = "ID";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.id
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    @ColumnDescription(desc = PROPERTY_REMARK_ID)
    @Id
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.name
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_NAME = "name";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.name
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_REMARK_NAME = "车主姓名";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.name
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    @ColumnDescription(desc = PROPERTY_REMARK_NAME)
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.age
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_AGE = "age";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.age
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_REMARK_AGE = "年龄";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.age
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    @ColumnDescription(desc = PROPERTY_REMARK_AGE)
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.driving_license
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_DRIVINGLICENSE = "drivingLicense";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.driving_license
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_REMARK_DRIVINGLICENSE = "驾照类型";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.driving_license
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    @ColumnDescription(desc = PROPERTY_REMARK_DRIVINGLICENSE)
    private Integer drivingLicense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.identity_no
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_IDENTITYNO = "identityNo";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.identity_no
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_REMARK_IDENTITYNO = "身份证号";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.identity_no
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    @ColumnDescription(desc = PROPERTY_REMARK_IDENTITYNO)
    private String identityNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.telephone
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_TELEPHONE = "telephone";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.telephone
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_REMARK_TELEPHONE = "手机号";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.telephone
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    @ColumnDescription(desc = PROPERTY_REMARK_TELEPHONE)
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.plate_no
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_PLATENO = "plateNo";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.plate_no
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_REMARK_PLATENO = "车牌号";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.plate_no
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    @ColumnDescription(desc = PROPERTY_REMARK_PLATENO)
    private String plateNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.car_type
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_CARTYPE = "carType";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.car_type
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_REMARK_CARTYPE = "车型（1为私家车，2为集团车）";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.car_type
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    @ColumnDescription(desc = PROPERTY_REMARK_CARTYPE)
    private Integer carType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.phone_of_device
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_PHONEOFDEVICE = "phoneOfDevice";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.phone_of_device
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_REMARK_PHONEOFDEVICE = "设备SIM卡号";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.phone_of_device
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    @ColumnDescription(desc = PROPERTY_REMARK_PHONEOFDEVICE)
    private String phoneOfDevice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.device_id
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_DEVICEID = "deviceId";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.device_id
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_REMARK_DEVICEID = "设备ID";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.device_id
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    @ColumnDescription(desc = PROPERTY_REMARK_DEVICEID)
    private Integer deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.weixin_account
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_WEIXINACCOUNT = "weixinAccount";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.weixin_account
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_REMARK_WEIXINACCOUNT = "微信账号";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.weixin_account
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    @ColumnDescription(desc = PROPERTY_REMARK_WEIXINACCOUNT)
    private String weixinAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.create_time
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_CREATETIME = "createTime";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.create_time
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_REMARK_CREATETIME = "录入时间";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.create_time
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    @ColumnDescription(desc = PROPERTY_REMARK_CREATETIME)
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.recorder_id
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_RECORDERID = "recorderId";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.recorder_id
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_REMARK_RECORDERID = "录入人ID";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.recorder_id
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    @ColumnDescription(desc = PROPERTY_REMARK_RECORDERID)
    private Integer recorderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.outofdate_time
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_OUTOFDATETIME = "outofdateTime";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.outofdate_time
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_REMARK_OUTOFDATETIME = "设备过期时间";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.outofdate_time
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    @ColumnDescription(desc = PROPERTY_REMARK_OUTOFDATETIME)
    private Date outofdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.activate_times
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_ACTIVATETIMES = "activateTimes";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.activate_times
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    private static final String PROPERTY_REMARK_ACTIVATETIMES = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `device_info`.activate_times
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    @ColumnDescription(desc = PROPERTY_REMARK_ACTIVATETIMES)
    private Integer activateTimes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column `device_info`.id
     *
     * @return the value of `device_info`.id
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column `device_info`.id
     *
     * @param id the value for `device_info`.id
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column `device_info`.name
     *
     * @return the value of `device_info`.name
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column `device_info`.name
     *
     * @param name the value for `device_info`.name
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column `device_info`.age
     *
     * @return the value of `device_info`.age
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column `device_info`.age
     *
     * @param age the value for `device_info`.age
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column `device_info`.driving_license
     *
     * @return the value of `device_info`.driving_license
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public Integer getDrivingLicense() {
        return drivingLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column `device_info`.driving_license
     *
     * @param drivingLicense the value for `device_info`.driving_license
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public void setDrivingLicense(Integer drivingLicense) {
        this.drivingLicense = drivingLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column `device_info`.identity_no
     *
     * @return the value of `device_info`.identity_no
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public String getIdentityNo() {
        return identityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column `device_info`.identity_no
     *
     * @param identityNo the value for `device_info`.identity_no
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public void setIdentityNo(String identityNo) {
        this.identityNo = identityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column `device_info`.telephone
     *
     * @return the value of `device_info`.telephone
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column `device_info`.telephone
     *
     * @param telephone the value for `device_info`.telephone
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column `device_info`.plate_no
     *
     * @return the value of `device_info`.plate_no
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public String getPlateNo() {
        return plateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column `device_info`.plate_no
     *
     * @param plateNo the value for `device_info`.plate_no
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public void setPlateNo(String plateNo) {
        this.plateNo = plateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column `device_info`.car_type
     *
     * @return the value of `device_info`.car_type
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public Integer getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column `device_info`.car_type
     *
     * @param carType the value for `device_info`.car_type
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public void setCarType(Integer carType) {
        this.carType = carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column `device_info`.phone_of_device
     *
     * @return the value of `device_info`.phone_of_device
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public String getPhoneOfDevice() {
        return phoneOfDevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column `device_info`.phone_of_device
     *
     * @param phoneOfDevice the value for `device_info`.phone_of_device
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public void setPhoneOfDevice(String phoneOfDevice) {
        this.phoneOfDevice = phoneOfDevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column `device_info`.device_id
     *
     * @return the value of `device_info`.device_id
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column `device_info`.device_id
     *
     * @param deviceId the value for `device_info`.device_id
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column `device_info`.weixin_account
     *
     * @return the value of `device_info`.weixin_account
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public String getWeixinAccount() {
        return weixinAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column `device_info`.weixin_account
     *
     * @param weixinAccount the value for `device_info`.weixin_account
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public void setWeixinAccount(String weixinAccount) {
        this.weixinAccount = weixinAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column `device_info`.create_time
     *
     * @return the value of `device_info`.create_time
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column `device_info`.create_time
     *
     * @param createTime the value for `device_info`.create_time
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column `device_info`.recorder_id
     *
     * @return the value of `device_info`.recorder_id
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public Integer getRecorderId() {
        return recorderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column `device_info`.recorder_id
     *
     * @param recorderId the value for `device_info`.recorder_id
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public void setRecorderId(Integer recorderId) {
        this.recorderId = recorderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column `device_info`.outofdate_time
     *
     * @return the value of `device_info`.outofdate_time
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public Date getOutofdateTime() {
        return outofdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column `device_info`.outofdate_time
     *
     * @param outofdateTime the value for `device_info`.outofdate_time
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public void setOutofdateTime(Date outofdateTime) {
        this.outofdateTime = outofdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column `device_info`.activate_times
     *
     * @return the value of `device_info`.activate_times
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public Integer getActivateTimes() {
        return activateTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column `device_info`.activate_times
     *
     * @param activateTimes the value for `device_info`.activate_times
     *
     * @mbggenerated 2015-12-10 09:17:05
     */
    public void setActivateTimes(Integer activateTimes) {
        this.activateTimes = activateTimes;
    }
}