/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package com.tyj.dao.demo.taskStatus.bo;

import cn.vansky.framework.core.dao.FieldAccessVo;
import cn.vansky.framework.core.dao.TableDataConvertable;
import cn.vansky.framework.core.dao.annotation.ColumnDescription;
import cn.vansky.framework.core.dao.annotation.Id;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table `tb_task_status`
 *
 * @mbggenerated 2015-12-22 10:50:37
 */
public abstract class TaskStatusBase extends FieldAccessVo implements TableDataConvertable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `tb_task_status`.id
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    private static final String PROPERTY_ID = "id";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `tb_task_status`.id
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    private static final String PROPERTY_REMARK_ID = "ID";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `tb_task_status`.id
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    @ColumnDescription(desc = PROPERTY_REMARK_ID)
    @Id
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `tb_task_status`.system_id
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    private static final String PROPERTY_SYSTEMID = "systemId";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `tb_task_status`.system_id
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    private static final String PROPERTY_REMARK_SYSTEMID = "系统ID";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `tb_task_status`.system_id
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    @ColumnDescription(desc = PROPERTY_REMARK_SYSTEMID)
    private Integer systemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `tb_task_status`.system_unique_id
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    private static final String PROPERTY_SYSTEMUNIQUEID = "systemUniqueId";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `tb_task_status`.system_unique_id
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    private static final String PROPERTY_REMARK_SYSTEMUNIQUEID = "系统唯一标识";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `tb_task_status`.system_unique_id
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    @ColumnDescription(desc = PROPERTY_REMARK_SYSTEMUNIQUEID)
    private Integer systemUniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `tb_task_status`.drive_time
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    private static final String PROPERTY_DRIVETIME = "driveTime";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `tb_task_status`.drive_time
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    private static final String PROPERTY_REMARK_DRIVETIME = "执行时间";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `tb_task_status`.drive_time
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    @ColumnDescription(desc = PROPERTY_REMARK_DRIVETIME)
    private Date driveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `tb_task_status`.task_type
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    private static final String PROPERTY_TASKTYPE = "taskType";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `tb_task_status`.task_type
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    private static final String PROPERTY_REMARK_TASKTYPE = "任务类型";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `tb_task_status`.task_type
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    @ColumnDescription(desc = PROPERTY_REMARK_TASKTYPE)
    private Integer taskType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `tb_task_status`.status
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    private static final String PROPERTY_STATUS = "status";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `tb_task_status`.status
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    private static final String PROPERTY_REMARK_STATUS = "状态";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column `tb_task_status`.status
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    @ColumnDescription(desc = PROPERTY_REMARK_STATUS)
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column `tb_task_status`.id
     *
     * @return the value of `tb_task_status`.id
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column `tb_task_status`.id
     *
     * @param id the value for `tb_task_status`.id
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column `tb_task_status`.system_id
     *
     * @return the value of `tb_task_status`.system_id
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    public Integer getSystemId() {
        return systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column `tb_task_status`.system_id
     *
     * @param systemId the value for `tb_task_status`.system_id
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    public void setSystemId(Integer systemId) {
        this.systemId = systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column `tb_task_status`.system_unique_id
     *
     * @return the value of `tb_task_status`.system_unique_id
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    public Integer getSystemUniqueId() {
        return systemUniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column `tb_task_status`.system_unique_id
     *
     * @param systemUniqueId the value for `tb_task_status`.system_unique_id
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    public void setSystemUniqueId(Integer systemUniqueId) {
        this.systemUniqueId = systemUniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column `tb_task_status`.drive_time
     *
     * @return the value of `tb_task_status`.drive_time
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    public Date getDriveTime() {
        return driveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column `tb_task_status`.drive_time
     *
     * @param driveTime the value for `tb_task_status`.drive_time
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    public void setDriveTime(Date driveTime) {
        this.driveTime = driveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column `tb_task_status`.task_type
     *
     * @return the value of `tb_task_status`.task_type
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    public Integer getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column `tb_task_status`.task_type
     *
     * @param taskType the value for `tb_task_status`.task_type
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    public void setTaskType(Integer taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column `tb_task_status`.status
     *
     * @return the value of `tb_task_status`.status
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column `tb_task_status`.status
     *
     * @param status the value for `tb_task_status`.status
     *
     * @mbggenerated 2015-12-22 10:50:37
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}