/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package com.tyj.dao.demo.taskStatus.bo;

import cn.vansky.framework.common.util.DateUtil;
import org.apache.commons.collections.MapUtils;

import java.util.Date;
import java.util.Map;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table `tb_task_status`
 *
 * @mbggenerated 2015-12-22 10:50:37
 */
public class TaskStatus extends TaskStatusBase {

    public static final int EXPORT_DEVICE_INFO = 1;

    public static final int EXPORT_DEVICE_GPS_INFO = 2;

    public static final int EXPORT_DEVICE_GPS_INFO_COUNT = 3;

    public static final int OVER_STATUS = 2;

    public static final int SYSTEM_ID = 2;

    public static TaskStatus addTaskStatus(Map<String, Object> params) {
        TaskStatus s = new TaskStatus();
        s.setSystemId(MapUtils.getInteger(params, "systemId"));
        Date date = DateUtil.parse(DateUtil.yyyy_MM_dd, MapUtils.getString(params, "startDate"));
        s.setDriveTime(date);
        s.setTaskType(MapUtils.getInteger(params, "taskType"));
        s.setStatus(MapUtils.getInteger(params, "status"));
        s.setSystemUniqueId(MapUtils.getInteger(params, "deviceId", 0));
        return s;
    }
}