/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package com.tyj.dao.demo.old.dao.impl;

import cn.vansky.framework.core.dao.ConfigurableBaseSqlMapDao;
import cn.vansky.framework.core.dao.DaoMapper;
import com.tyj.dao.demo.old.bo.FactorWarning;
import com.tyj.dao.demo.old.dao.FactorWarningDao;
import com.tyj.dao.demo.old.dao.FactorWarningMapper;
import java.util.HashMap;
import javax.annotation.Resource;
import org.apache.ibatis.session.SqlSessionFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table `factor_warning`
 *
 * @mbggenerated 2015-12-27 13:43:44
 */
@Repository("factorWarningDao")
public class FactorWarningDaoImpl extends ConfigurableBaseSqlMapDao<FactorWarning, HashMap> implements FactorWarningDao {
    @Autowired
    private FactorWarningMapper factorWarningMapper;

    @Override
    public DaoMapper<FactorWarning, HashMap> getDaoMapper() {
        return factorWarningMapper;
    }

    @Resource(name = "sqlSessionFactory")
    @Override
    public void setSqlSessionFactory(SqlSessionFactory sqlSessionFactory) {
        setSqlSessionFactoryInternal(sqlSessionFactory);
    }
}