/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package com.tyj.dao.demo.old.dao;

import cn.vansky.framework.core.dao.SqlMapDao;
import com.tyj.dao.demo.old.bo.FactorWarning;
import java.util.HashMap;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table `factor_warning`
 *
 * @mbggenerated 2015-12-27 13:43:44
 */
public interface FactorWarningDao extends SqlMapDao<FactorWarning, HashMap> {
}