/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package com.tyj.service.demo.taskStatus.service.impl;

import cn.vansky.framework.core.dao.SqlMapDao;
import cn.vansky.framework.core.service.GenericSqlMapServiceImpl;
import com.tyj.dao.demo.taskStatus.bo.TaskStatus;
import com.tyj.dao.demo.taskStatus.dao.TaskStatusDao;
import com.tyj.service.demo.taskStatus.service.TaskStatusService;
import javax.annotation.Resource;
import org.springframework.stereotype.Service;

import java.util.Map;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table `tb_task_status`
 *
 * @mbggenerated 2015-12-22 10:50:37
 */
@Service("taskStatusService")
public class TaskStatusServiceImpl extends GenericSqlMapServiceImpl<TaskStatus, Integer> implements TaskStatusService {
    @Resource(name = "taskStatusDao")
    private TaskStatusDao taskStatusDao;

    @Override
    public SqlMapDao<TaskStatus, Integer> getDao() {
        return taskStatusDao;
    }

    @Override
    public TaskStatus findTaskStatus(Map<String, Object> params) {
        return taskStatusDao.findTaskStatus(params);
    }
}