/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package com.tyj.service.demo.deviceGpsInfos.service.impl;

import cn.vansky.framework.common.util.DateUtil;
import cn.vansky.framework.core.dao.SqlMapDao;
import cn.vansky.framework.core.service.GenericSqlMapServiceImpl;
import com.tyj.dao.demo.deviceGpsInfos.bo.DeviceGpsInfosCount;
import com.tyj.dao.demo.deviceGpsInfos.dao.DeviceGpsInfosCountDao;
import com.tyj.service.demo.deviceGpsInfos.service.DeviceGpsInfosCountService;
import javax.annotation.Resource;
import org.springframework.stereotype.Service;

import java.util.Date;
import java.util.List;
import java.util.Map;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table `device_gps_infos_count`
 *
 * @mbggenerated 2015-12-30 16:45:19
 */
@Service("deviceGpsInfosCountService")
public class DeviceGpsInfosCountServiceImpl extends GenericSqlMapServiceImpl<DeviceGpsInfosCount, Integer> implements DeviceGpsInfosCountService {
    @Resource(name = "deviceGpsInfosCountDao")
    private DeviceGpsInfosCountDao deviceGpsInfosCountDao;

    @Override
    public SqlMapDao<DeviceGpsInfosCount, Integer> getDao() {
        return deviceGpsInfosCountDao;
    }

    @Override
    public void delByDeviceIdAndTime(Map<String, Object> params) {
        deviceGpsInfosCountDao.delByDeviceIdAndTime(params);
    }

    @Override
    public List<DeviceGpsInfosCount> findParams(Map<String, Object> params) {
        return deviceGpsInfosCountDao.findParams(params);
    }

    @Override
    public List<DeviceGpsInfosCount> findTotalAlarm(Map<String, Object> params) {
        Date date = DateUtil.parse(DateUtil.yyyyMM, params.get("date").toString());
        String startDate = DateUtil.dateRedMonthBegin(date, 0) + " 00:00:00";
        String endDate = DateUtil.dateRedMonthEnd(date, 0) + " 23:59:59";
        params.put("startDate", startDate);
        params.put("endDate", endDate);
        String [] ds = params.get("deviceId").toString().split(",");
        params.put("ds", ds);
        return deviceGpsInfosCountDao.findTotalAlarm(params);
    }
}