/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package com.tyj.service.demo.deviceGpsInfos.service.impl;

import cn.vansky.framework.core.dao.SqlMapDao;
import cn.vansky.framework.core.service.GenericSqlMapServiceImpl;
import com.tyj.dao.demo.deviceGpsInfos.bo.DeviceGpsInfos;
import com.tyj.dao.demo.deviceGpsInfos.dao.DeviceGpsInfosDao;
import com.tyj.service.demo.deviceGpsInfos.service.DeviceGpsInfosService;
import org.springframework.stereotype.Service;

import javax.annotation.Resource;
import java.util.List;
import java.util.Map;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table `device_gps_infos`
 *
 * @mbggenerated 2015-12-09 08:31:58
 */
@Service("deviceGpsInfosService")
public class DeviceGpsInfosServiceImpl extends GenericSqlMapServiceImpl<DeviceGpsInfos, Integer> implements DeviceGpsInfosService {
    @Resource(name = "deviceGpsInfosDao")
    private DeviceGpsInfosDao deviceGpsInfosDao;

    @Override
    public SqlMapDao<DeviceGpsInfos, Integer> getDao() {
        return deviceGpsInfosDao;
    }

    @Override
    public List<DeviceGpsInfos> findDaySpeed(Map<String, Object> params) {
        return deviceGpsInfosDao.findDaySpeed(params);
    }

    @Override
    public List<Map<String, Object>> findByDeviceIds(List<Integer> list) {
        return deviceGpsInfosDao.findByDeviceIds(list);
    }

    @Override
    public void delByDeviceIdAndTime(Map<String, Object> params) {
        deviceGpsInfosDao.delByDeviceIdAndTime(params);
    }

    @Override
    public List<Map<String, Object>> findAlarmMessage(Map<String, Object> params) {
        return deviceGpsInfosDao.findAlarmMessage(params);
    }

    @Override
    public List<DeviceGpsInfos> findByDeviceIdAndTime(Map<String, Object> params) {
        return deviceGpsInfosDao.findByDeviceIdAndTime(params);
    }

    @Override
    public List<DeviceGpsInfos> findByDeviceIdAndTypes(Map<String, Object> params) {
        return deviceGpsInfosDao.findByDeviceIdAndTypes(params);
    }

    @Override
    public void createPartition(Map<String, Object> params) {
        deviceGpsInfosDao.createPartition(params);
    }

    @Override
    public List<DeviceGpsInfos> findLocation(Map<String, Object> params) {
        return deviceGpsInfosDao.findLocation(params);
    }
}