/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package com.tyj.dao.demo.taskStatus.dao.impl;

import cn.vansky.framework.core.dao.ConfigurableBaseSqlMapDao;
import cn.vansky.framework.core.dao.DaoMapper;
import com.tyj.dao.demo.taskStatus.bo.TaskStatus;
import com.tyj.dao.demo.taskStatus.dao.TaskStatusDao;
import com.tyj.dao.demo.taskStatus.dao.TaskStatusMapper;
import javax.annotation.Resource;
import org.apache.ibatis.session.SqlSessionFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table `tb_task_status`
 *
 * @mbggenerated 2015-12-22 10:50:37
 */
@Repository("taskStatusDao")
public class TaskStatusDaoImpl extends ConfigurableBaseSqlMapDao<TaskStatus, Integer> implements TaskStatusDao {
    @Autowired
    private TaskStatusMapper taskStatusMapper;

    @Override
    public DaoMapper<TaskStatus, Integer> getDaoMapper() {
        return taskStatusMapper;
    }

    @Resource(name = "sqlSessionFactory")
    @Override
    public void setSqlSessionFactory(SqlSessionFactory sqlSessionFactory) {
        setSqlSessionFactoryInternal(sqlSessionFactory);
    }

    @Override
    public TaskStatus findTaskStatus(Map<String, Object> params) {
        return taskStatusMapper.findTaskStatus(params);
    }
}