/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package com.tyj.dao.demo.old.bo;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table `factor_warning`
 *
 * @mbggenerated 2015-12-27 13:43:44
 */
public class FactorWarning extends FactorWarningBase {
    /**
     * 速度
     */
    public static final int SPEED_FACTOR = 1;
    /**
     * 驾驶时长
     */
    public static final int DAY_DRIVER_TIME = 2;
    /**
     * 前后间隔时间
     */
    public static final int TIME_DIFF = 3;
    /**
     * 天气因素
     */
    public static final int WEATHER = 4;
    /**
     * 疲劳度
     */
    public static final int FATIGUE = 5;
    /**
     * 能见度
     */
    public static final int VISIBILITY = 6;
    /**
     * 前天因素
     */
    public static final int PREV_DAY = 7;
}