/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package com.tyj.dao.demo.deviceGpsInfos.bo;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table `device_gps_infos_count`
 *
 * @mbggenerated 2015-12-30 16:45:19
 */
public class DeviceGpsInfosCount extends DeviceGpsInfosCountBase {
    public DeviceGpsInfosCount() {
        setDeviceId(0);
        setDriveTime(0.0);
        setCarFrontCollide(0);
        setLimitSpeedAlarm(0);
        setLeftLaneDeviate(0);
        setCityFrontCollide(0);
        setCityFrontCollide(0);
        setCarDistanceMonitor(0);
        setRightLaneDeviate(0);
        setCarStart(0);
        setCarEnd(0);
        setLocationMessage(0);
        setSpeedUp(0);
        setSpeedDown(0);
        setVdNoStart(0);
        setDeviceActive(0);
        setPersonFrontCollide(0);
        setCollideFollow(0);
        setDeviceSetSuccess(0);
        setDeviceSetFail(0);
        setScores(0.0);
        setSum(0.0);
        setCarCollideFollow(0);
        setPersonCollideFollow(0);
        setOneCarFrontCollide(0);
        setTwoCarFrontCollide(0);
        setOverSpeedFollow(0);
        setOverSpeedAlarm(0);
    }
}