/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package com.tyj.service.jhpt.deviceGpsInfos.service.impl;

import cn.vansky.framework.core.dao.SqlMapDao;
import cn.vansky.framework.core.service.GenericSqlMapServiceImpl;
import com.tyj.dao.jhpt.deviceGpsInfos.bo.DeviceGpsInfos;
import com.tyj.dao.jhpt.deviceGpsInfos.dao.DeviceGpsInfosJhptDao;
import com.tyj.service.jhpt.deviceGpsInfos.service.DeviceGpsInfosServiceJhpt;
import javax.annotation.Resource;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table `device_gps_infos`
 *
 * @mbggenerated 2015-12-10 09:17:05
 */
@Service("deviceGpsInfosServiceJhpt")
public class DeviceGpsInfosServiceJhptImpl extends GenericSqlMapServiceImpl<DeviceGpsInfos, Integer> implements DeviceGpsInfosServiceJhpt {
    @Resource(name = "deviceGpsInfosDaoJhpt")
    private DeviceGpsInfosJhptDao deviceGpsInfosDao;

    @Override
    public SqlMapDao<DeviceGpsInfos, Integer> getDao() {
        return deviceGpsInfosDao;
    }

    @Override
    public List<DeviceGpsInfos> findByDeviceIdAndTime(Map<String, Object> params) {
        return deviceGpsInfosDao.findByDeviceIdAndTime(params);
    }
}