/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package com.tyj.dao.jhpt.deviceGpsInfos.dao.impl;

import cn.vansky.framework.core.dao.ConfigurableBaseSqlMapDao;
import cn.vansky.framework.core.dao.DaoMapper;
import com.tyj.dao.jhpt.deviceGpsInfos.bo.DeviceGpsInfos;
import com.tyj.dao.jhpt.deviceGpsInfos.dao.DeviceGpsInfosJhptDao;
import com.tyj.dao.jhpt.deviceGpsInfos.dao.DeviceGpsInfosJhptMapper;

import javax.annotation.Resource;
import org.apache.ibatis.session.SqlSessionFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table `device_gps_infos`
 *
 * @mbggenerated 2015-12-10 09:17:05
 */
@Repository("deviceGpsInfosDaoJhpt")
public class DeviceGpsInfosJhptDaoImpl extends ConfigurableBaseSqlMapDao<DeviceGpsInfos, Integer> implements DeviceGpsInfosJhptDao {
    @Autowired
    private DeviceGpsInfosJhptMapper deviceGpsInfosMapper;

    @Override
    public DaoMapper<DeviceGpsInfos, Integer> getDaoMapper() {
        return deviceGpsInfosMapper;
    }

    @Resource(name = "sqlSessionFactoryJhpt")
    @Override
    public void setSqlSessionFactory(SqlSessionFactory sqlSessionFactory) {
        setSqlSessionFactoryInternal(sqlSessionFactory);
    }

    @Override
    public List<DeviceGpsInfos> findByDeviceIdAndTime(Map<String, Object> params) {
        return deviceGpsInfosMapper.findByDeviceIdAndTime(params);
    }
}