/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package com.tyj.dao.demo.deviceGpsInfos.dao.impl;

import cn.vansky.framework.core.dao.ConfigurableBaseSqlMapDao;
import cn.vansky.framework.core.dao.DaoMapper;
import com.tyj.dao.demo.deviceGpsInfos.bo.DeviceGpsInfosCount;
import com.tyj.dao.demo.deviceGpsInfos.dao.DeviceGpsInfosCountDao;
import com.tyj.dao.demo.deviceGpsInfos.dao.DeviceGpsInfosCountMapper;
import javax.annotation.Resource;

import org.apache.ibatis.session.SqlSessionFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table `device_gps_infos_count`
 *
 * @mbggenerated 2015-12-30 16:45:19
 */
@Repository("deviceGpsInfosCountDao")
public class DeviceGpsInfosCountDaoImpl extends ConfigurableBaseSqlMapDao<DeviceGpsInfosCount, Integer> implements DeviceGpsInfosCountDao {
    @Autowired
    private DeviceGpsInfosCountMapper deviceGpsInfosCountMapper;

    @Override
    public DaoMapper<DeviceGpsInfosCount, Integer> getDaoMapper() {
        return deviceGpsInfosCountMapper;
    }

    @Resource(name = "sqlSessionFactory")
    @Override
    public void setSqlSessionFactory(SqlSessionFactory sqlSessionFactory) {
        setSqlSessionFactoryInternal(sqlSessionFactory);
    }

    @Override
    public void delByDeviceIdAndTime(Map<String, Object> params) {
        deviceGpsInfosCountMapper.delByDeviceIdAndTime(params);
    }

    @Override
    public List<DeviceGpsInfosCount> findParams(Map<String, Object> params) {
        return deviceGpsInfosCountMapper.findParams(params);
    }

    @Override
    public List<DeviceGpsInfosCount> findTotalAlarm(Map<String, Object> params) {
        return deviceGpsInfosCountMapper.findTotalAlarm(params);
    }
}