/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package com.tyj.dao.jhpt.deviceInfo.dao;

import cn.vansky.framework.core.dao.DaoMapper;
import cn.vansky.framework.core.orm.mybatis.annotation.SqlMapper;
import com.tyj.dao.jhpt.deviceInfo.bo.DeviceInfo;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table `device_info`
 *
 * @mbggenerated 2015-12-10 09:17:05
 */
@SqlMapper
public interface DeviceInfoJhptMapper extends DaoMapper<DeviceInfo, Integer> {
}