/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package com.tyj.dao.jhpt.deviceInfo.dao;

import cn.vansky.framework.core.dao.SqlMapDao;
import com.tyj.dao.jhpt.deviceInfo.bo.DeviceInfo;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table `device_info`
 *
 * @mbggenerated 2015-12-10 09:17:05
 */
public interface DeviceInfoJhptDao extends SqlMapDao<DeviceInfo, Integer> {
}