/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package com.tyj.service.jhpt.deviceGpsInfos.service;

import cn.vansky.framework.core.service.GenericService;
import com.tyj.dao.jhpt.deviceGpsInfos.bo.DeviceGpsInfos;

import java.util.List;
import java.util.Map;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table `device_gps_infos`
 *
 * @mbggenerated 2015-12-10 09:17:05
 */
public interface DeviceGpsInfosServiceJhpt extends GenericService<DeviceGpsInfos, Integer> {

    List<DeviceGpsInfos> findByDeviceIdAndTime(Map<String, Object> params);
}