/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package com.tyj.dao.demo.taskStatus.dao;

import cn.vansky.framework.core.dao.DaoMapper;
import cn.vansky.framework.core.orm.mybatis.annotation.SqlMapper;
import com.tyj.dao.demo.taskStatus.bo.TaskStatus;

import java.util.List;
import java.util.Map;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table `tb_task_status`
 *
 * @mbggenerated 2015-12-22 10:50:37
 */
@SqlMapper
public interface TaskStatusMapper extends DaoMapper<TaskStatus, Integer> {

     TaskStatus findTaskStatus(Map<String, Object> params);
}